language: node_js
node_js: 14.15.4
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - npm run cover
  after_success:
  - npm run coveralls
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=jzavalaq-github -Dsonar.projectKey=CalculatorNodeJS -Dsonar.sources='./app' -X
